name: ProCom # env name
channels:  # channel to make the instalation 
- anaconda
- pytorch
- defaults
dependencies:
- python=3.9
- pip
- conda-forge::numpy=1.21.*
- conda-forge::python-box
- conda-forge::pytorch=2.1.*
- pandas
- transform  
- tqdm
- pprint
- pip:
  - iopath
