name: Calculate Lines Committed by Contributors

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  calculate-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests regex

    - name: Execute Python Script
      run: python .github/workflows/calculate_lines.py
      env:
        owner: NewS0ul
        repo: ProCom
        GITHUB_TOKEN: ${{ secrets.TOKEN }} # add secret named TOKEN

    - name: Commit and push updated README.md
      run: |
        git config --global user.email "kikimeter@bot.com"
        git config --global user.name "kikimeter"
        git add README.md
        git commit -m "Update KIKIMETER"
        git push
      working-directory: ${{ github.workspace }}

